//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStudyRooms.SOAPClient.SoapSalasReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sala", Namespace="http://schemas.datacontract.org/2004/07/SmartStudyRooms.Data.Models")]
    [System.SerializableAttribute()]
    public partial class Sala : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CapacidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OcupadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReservadaAteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacidade {
            get {
                return this.CapacidadeField;
            }
            set {
                if ((this.CapacidadeField.Equals(value) != true)) {
                    this.CapacidadeField = value;
                    this.RaisePropertyChanged("Capacidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ocupada {
            get {
                return this.OcupadaField;
            }
            set {
                if ((this.OcupadaField.Equals(value) != true)) {
                    this.OcupadaField = value;
                    this.RaisePropertyChanged("Ocupada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReservadaAte {
            get {
                return this.ReservadaAteField;
            }
            set {
                if ((this.ReservadaAteField.Equals(value) != true)) {
                    this.ReservadaAteField = value;
                    this.RaisePropertyChanged("ReservadaAte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalaId {
            get {
                return this.SalaIdField;
            }
            set {
                if ((this.SalaIdField.Equals(value) != true)) {
                    this.SalaIdField = value;
                    this.RaisePropertyChanged("SalaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smartstudyrooms.ipca.pt/soap", ConfigurationName="SoapSalasReference.ISalaSoapService")]
    public interface ISalaSoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/ListarSalas", ReplyAction="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/ListarSalasResponse")]
        SmartStudyRooms.SOAPClient.SoapSalasReference.Sala[] ListarSalas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/ListarSalas", ReplyAction="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/ListarSalasResponse")]
        System.Threading.Tasks.Task<SmartStudyRooms.SOAPClient.SoapSalasReference.Sala[]> ListarSalasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/ObterSala", ReplyAction="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/ObterSalaResponse")]
        SmartStudyRooms.SOAPClient.SoapSalasReference.Sala ObterSala(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/ObterSala", ReplyAction="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/ObterSalaResponse")]
        System.Threading.Tasks.Task<SmartStudyRooms.SOAPClient.SoapSalasReference.Sala> ObterSalaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/CriarSala", ReplyAction="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/CriarSalaResponse")]
        int CriarSala(SmartStudyRooms.SOAPClient.SoapSalasReference.Sala sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/CriarSala", ReplyAction="http://smartstudyrooms.ipca.pt/soap/ISalaSoapService/CriarSalaResponse")]
        System.Threading.Tasks.Task<int> CriarSalaAsync(SmartStudyRooms.SOAPClient.SoapSalasReference.Sala sala);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaSoapServiceChannel : SmartStudyRooms.SOAPClient.SoapSalasReference.ISalaSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaSoapServiceClient : System.ServiceModel.ClientBase<SmartStudyRooms.SOAPClient.SoapSalasReference.ISalaSoapService>, SmartStudyRooms.SOAPClient.SoapSalasReference.ISalaSoapService {
        
        public SalaSoapServiceClient() {
        }
        
        public SalaSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SmartStudyRooms.SOAPClient.SoapSalasReference.Sala[] ListarSalas() {
            return base.Channel.ListarSalas();
        }
        
        public System.Threading.Tasks.Task<SmartStudyRooms.SOAPClient.SoapSalasReference.Sala[]> ListarSalasAsync() {
            return base.Channel.ListarSalasAsync();
        }
        
        public SmartStudyRooms.SOAPClient.SoapSalasReference.Sala ObterSala(int id) {
            return base.Channel.ObterSala(id);
        }
        
        public System.Threading.Tasks.Task<SmartStudyRooms.SOAPClient.SoapSalasReference.Sala> ObterSalaAsync(int id) {
            return base.Channel.ObterSalaAsync(id);
        }
        
        public int CriarSala(SmartStudyRooms.SOAPClient.SoapSalasReference.Sala sala) {
            return base.Channel.CriarSala(sala);
        }
        
        public System.Threading.Tasks.Task<int> CriarSalaAsync(SmartStudyRooms.SOAPClient.SoapSalasReference.Sala sala) {
            return base.Channel.CriarSalaAsync(sala);
        }
    }
}
