<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Content Remove="connection.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="connection.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartStudyRooms.Data\SmartStudyRooms.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>


</Project>
