//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartStudyRooms.SOAPClient.SoapReservasReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/SmartStudyRooms.Data.Models")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativa {
            get {
                return this.AtivaField;
            }
            set {
                if ((this.AtivaField.Equals(value) != true)) {
                    this.AtivaField = value;
                    this.RaisePropertyChanged("Ativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fim {
            get {
                return this.FimField;
            }
            set {
                if ((this.FimField.Equals(value) != true)) {
                    this.FimField = value;
                    this.RaisePropertyChanged("Fim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((this.InicioField.Equals(value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservaId {
            get {
                return this.ReservaIdField;
            }
            set {
                if ((this.ReservaIdField.Equals(value) != true)) {
                    this.ReservaIdField = value;
                    this.RaisePropertyChanged("ReservaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalaId {
            get {
                return this.SalaIdField;
            }
            set {
                if ((this.SalaIdField.Equals(value) != true)) {
                    this.SalaIdField = value;
                    this.RaisePropertyChanged("SalaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapReservasReference.IReservaSoapService")]
    public interface IReservaSoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaSoapService/ListarReservas", ReplyAction="http://tempuri.org/IReservaSoapService/ListarReservasResponse")]
        SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva[] ListarReservas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaSoapService/ListarReservas", ReplyAction="http://tempuri.org/IReservaSoapService/ListarReservasResponse")]
        System.Threading.Tasks.Task<SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva[]> ListarReservasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaSoapService/ObterReserva", ReplyAction="http://tempuri.org/IReservaSoapService/ObterReservaResponse")]
        SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva ObterReserva(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaSoapService/ObterReserva", ReplyAction="http://tempuri.org/IReservaSoapService/ObterReservaResponse")]
        System.Threading.Tasks.Task<SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva> ObterReservaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaSoapService/CriarReserva", ReplyAction="http://tempuri.org/IReservaSoapService/CriarReservaResponse")]
        void CriarReserva(SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaSoapService/CriarReserva", ReplyAction="http://tempuri.org/IReservaSoapService/CriarReservaResponse")]
        System.Threading.Tasks.Task CriarReservaAsync(SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaSoapService/CancelarReserva", ReplyAction="http://tempuri.org/IReservaSoapService/CancelarReservaResponse")]
        void CancelarReserva(int reservaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaSoapService/CancelarReserva", ReplyAction="http://tempuri.org/IReservaSoapService/CancelarReservaResponse")]
        System.Threading.Tasks.Task CancelarReservaAsync(int reservaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaSoapServiceChannel : SmartStudyRooms.SOAPClient.SoapReservasReference.IReservaSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaSoapServiceClient : System.ServiceModel.ClientBase<SmartStudyRooms.SOAPClient.SoapReservasReference.IReservaSoapService>, SmartStudyRooms.SOAPClient.SoapReservasReference.IReservaSoapService {
        
        public ReservaSoapServiceClient() {
        }
        
        public ReservaSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva[] ListarReservas() {
            return base.Channel.ListarReservas();
        }
        
        public System.Threading.Tasks.Task<SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva[]> ListarReservasAsync() {
            return base.Channel.ListarReservasAsync();
        }
        
        public SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva ObterReserva(int id) {
            return base.Channel.ObterReserva(id);
        }
        
        public System.Threading.Tasks.Task<SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva> ObterReservaAsync(int id) {
            return base.Channel.ObterReservaAsync(id);
        }
        
        public void CriarReserva(SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva reserva) {
            base.Channel.CriarReserva(reserva);
        }
        
        public System.Threading.Tasks.Task CriarReservaAsync(SmartStudyRooms.SOAPClient.SoapReservasReference.Reserva reserva) {
            return base.Channel.CriarReservaAsync(reserva);
        }
        
        public void CancelarReserva(int reservaId) {
            base.Channel.CancelarReserva(reservaId);
        }
        
        public System.Threading.Tasks.Task CancelarReservaAsync(int reservaId) {
            return base.Channel.CancelarReservaAsync(reservaId);
        }
    }
}
